# @Title: the_joker
# @Icon: mood-suprised
# @Color: #39ff14
# @Tag: THEME
# @Desc: Estética Joker: Verde ácido y morado profundo con resplandor eléctrico.

# -----------------------------------------------------
# Optimizado por NVL
# -----------------------------------------------------

general {
    border_size = 2

    # --- El Caos del Joker ---
    # Combinamos el Verde Neón (39ff14) con un Morado Eléctrico (9d00ff).
    # El color oscuro en medio (1a0026) es vital para que las luces parezcan separadas.
    col.active_border = rgba(39ff14ff) rgba(1a0026ff) rgba(9d00ffff) 45deg

    # Inactivo: Morado muy oscuro y sutil
    col.inactive_border = rgba(1a002655)
}

decoration {
    # --- Resplandor de Gotham ---
    shadow {
        enabled = true
        range = 18              # Un aura un poco más amplia para el efecto Joker
        render_power = 3

        # Usamos el morado intenso para la sombra.
        # Al girar el verde sobre este fondo morado, se crea un efecto óptico vibrante.
        color = rgba(9d00ff55)

        offset = 0 0
    }
}

animations {
    enabled = yes

    # Curva de flujo constante
    bezier = nv_joker_flow, 0.4, 0, 0.2, 1

    # Velocidad 30: Un giro constante que mantiene el dinamismo
    animation = borderangle, 1, 30, nv_joker_flow, loop
}
