# @Title: Relámpago
# @Icon: bolt
# @Color: #f87171
# @Tag: FAST
# @Desc: Máxima respuesta visual.

# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
animations {
    enabled = true

    # --- BEZIERS (CURVAS DE VELOCIDAD) ---
    # "Lightning": Empieza ultra rápido y frena en seco al final.
    bezier = lightning, 0.05, 0.9, 0.1, 1.05
    # "Smooth": Lineal pero suave para fades.
    bezier = smooth, 0.25, 1, 0.5, 1
    # "Instant": Casi instantáneo para movimiento.
    bezier = instant, 0, 1, 0, 1

    # --- VENTANAS (El núcleo del cambio) ---
    # Entrada: Muy rápida (Speed 2), aparece al 80% (menos recorrido visual).
    animation = windowsIn, 1, 2, lightning, popin 80%

    # Salida: Fugaz (Speed 1.5). Desaparece más rápido de lo que llegó.
    animation = windowsOut, 1, 1.5, lightning, popin 80%

    # Movimiento: Pegado al ratón. Speed 1.5 hace que se sienta eléctrico.
    animation = windowsMove, 1, 1.5, instant, slide

    # --- CAPAS Y FADES ---
    animation = fade, 1, 2, smooth
    animation = layers, 1, 2, lightning, fade
    animation = layersIn, 1, 2, lightning, fade
    animation = layersOut, 1, 1.5, lightning, fade

    # --- ESPACIOS DE TRABAJO ---
    # Slidefade: Desliza pero se desvanece un 20%. Da sensación de velocidad warp.
    animation = workspaces, 1, 2.5, lightning, slidefade 20%
    animation = specialWorkspace, 1, 2.5, lightning, slidevert
}
