# @Title: Seda Minimalista
# @Icon: circle-dot
# @Color: #818cf8
# @Tag: SOFT
# @Desc: Suavidad absoluta. Sin rebotes, solo aterrizajes perfectos estilo macOS.

# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#

animations {
    enabled = yes

    # --- BEZIERS (MATEMÁTICA PURA) ---
    # Quartic Out: La curva de la elegancia. Frena muy suavemente.
    bezier = quart, 0.25, 1, 0.5, 1

    # Expo Out: Para los escritorios, queremos que el final sea aún más suave.
    bezier = expo, 0.16, 1, 0.3, 1

    # --- VENTANAS (El cambio a Popin) ---
    # ENTRADA: 'popin 80%'. La ventana nace desde el centro (al 80% de tamaño) y crece.
    # Es mucho más elegante que verla volar desde un lado de la pantalla.
    animation = windowsIn, 1, 6, quart, popin 80%

    # SALIDA: Un poco más rápida (Velocidad 5) para que no estorbe.
    animation = windowsOut, 1, 5, quart, popin 80%

    # MOVIMIENTO: Usamos 'quart' para que la ventana tenga peso al arrastrarla.
    animation = windowsMove, 1, 6, quart, slide

    # --- CAPAS ---
    # Los menús se desvanecen suavemente.
    animation = fade, 1, 6, quart

    # --- ESPACIOS DE TRABAJO ---
    # AQUÍ ESTÁ EL TRUCO: 'slidefade 20%'
    # En lugar de solo deslizar, el escritorio viejo se oscurece un poco y se aleja.
    # Da una sensación de profundidad 3D muy sutil.
    animation = workspaces, 1, 6, expo, slidefade 20%
}
