# @Title: Futurista
# @Icon: cpu
# @Color: #22d3ee
# @Tag: TECH
# @Desc: Interfaz holográfica. Precisión digital, cero rebotes y flujo de datos vertical.

# -----------------------------------------------------
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#

# -----------------------------------------------------
# Optimizado por NVL: Eliminada la elasticidad.
# Ahora usa curvas exponenciales para una precisión "Robótica".
# -----------------------------------------------------

animations {
    enabled = true

    # --- BEZIERS TECH ---

    # "Holo": Curva Exponencial (Quint).
    # Sale disparada y frena en seco justo en el píxel exacto.
    bezier = holo, 0.23, 1, 0.32, 1

    # "Data": Lineal-Suavizada. Para flujos de información continuos.
    bezier = data, 0.16, 1, 0.3, 1

    # --- VENTANAS (Proyección) ---

    # ENTRADA: 'slide' desde abajo.
    # Parece que la ventana "emerge" de la consola.
    # Velocidad 5: Rápida pero visible.
    animation = windowsIn, 1, 5, holo, slide

    # SALIDA: 'popin 100%' + 'slide'.
    # La ventana no cambia de tamaño, simplemente se desliza y se apaga.
    # Velocidad 4: Desconexión rápida.
    animation = windowsOut, 1, 4, holo, popin 100%

    # MOVIMIENTO: Precisión quirúrgica.
    # La ventana sigue al ratón sin peso, como un cursor láser.
    animation = windowsMove, 1, 5, holo, slide

    # --- FADES (Digitales) ---
    animation = fade, 1, 5, data
    animation = layers, 1, 5, holo, fade

    # --- ESPACIOS DE TRABAJO (The Matrix Style) ---
    # AQUÍ ESTÁ LA CLAVE: 'slidevert' (Deslizamiento Vertical).
    # Cambiar de escritorio se siente como hacer scroll en una terminal gigante.
    # Muy "Cyberpunk".
    animation = workspaces, 1, 6, holo, slidevert

    # Special: Lo mismo, coherencia vertical total.
    animation = specialWorkspace, 1, 6, holo, slidevert
}
