# @Title: Neón
# @Icon: blur
# @Color: #cba6f7
# @Tag: GLITCH
# @Desc: Efecto "Cyberpunk". La luz del borde parpadea, avanza y retrocede como electricidad inestable.

#  _    _   ___    ____ _____  _    _      ___    _
# | \ | |/ _ \ / ___|_    _|/ \  | |    |_ _| / \
# |  \| | | | | |      | | / _ \ | |     | | / _ \
# | |\  | |_| | |___   | |/ ___ \| |___  | | / ___ \
# |_| \_|\___/ \____| |_/_/   \_\_____|___/_/   \_
#  ____    ___   ____   ____   ____ ____   ____
# | __ ) / _ \|  _ \|  _ \| __ |  _ \/ ___|
# |  _ \| | | | |_) | | | |  _ | |_) \___ \
# | |_) | |_| |  _ <| |_| | |__|  _ < ___) |
# |____/ \___/|_| \_\____/|____|_| \_\____/
#
# -----------------------------------------------------
# PRESET: 08_NEON_GLITCH (CYBERPUNK VERSION)
# -----------------------------------------------------

general {
    # ALTO CONTRASTE:
    # Alternamos el color primario con el fondo repetidas veces.
    # Esto crea "rayas" de luz en lugar de un degradado suave.
    # Parece el filamento de una bombilla o código de barras.
    col.active_border = $primary $surface $primary $surface $primary $surface 45deg

    col.inactive_border = $surface_lowest
}

animations {
    enabled = yes

    # --- LA CURVA "GLITCH" ---
    # Fíjate en los números negativos (-0.5) y excesivos (1.5).
    # Esto significa:
    # 1. Avanza rápido hacia adelante.
    # 2. ¡Retrocede! (El -0.5 hace que el giro vaya marcha atrás un instante).
    # 3. Vuelve a lanzarse hacia adelante (1.5).
    bezier = glitch, 0.1, 1.5, 0.9, -0.5

    # Velocidad 40: Un bucle de 4 segundos.
    # Al ser un loop infinito con esa curva loca, el borde parecerá que
    # está sufriendo interferencias eléctricas constantes.
    animation = borderangle, 1, 40, glitch, loop
}
