# @Title: Tóxico
# @Icon: biohazard
# @Color: #39ff14
# @Tag: ACID
# @Desc: Verde radiactivo intenso con efecto de flujo tóxico.

# -----------------------------------------------------
# Optimizado por NVL
# -----------------------------------------------------

general {
    # Grosor para que el efecto se aprecie bien
    border_size = 2

    # --- Efecto Flujo Radiactivo ---
    # Usamos Verde Neón (39ff14) + Negro Profundo (0c1017) + Verde Neón (39ff14)
    # Esto crea una "mancha" de luz que recorre el borde.
    col.active_border = rgba(39ff14ff) rgba(0c1017ff) rgba(39ff14ff) 30deg

    # Borde inactivo en un verde oscuro muy sutil
    col.inactive_border = rgba(022c0b55)
}

animations {
    enabled = yes

    # Curva suave para el movimiento del líquido
    bezier = nv_toxic, 0.4, 0, 0.2, 1

    # Velocidad 40: Un término medio entre lo frenético y lo elegante
    animation = borderangle, 1, 40, nv_toxic, loop
}
