# @Title: Neón Cyber-Glow (Dual)
# @Icon: bolt
# @Color: #00fff7
# @Tag: GLOW
# @Desc: Simulación de brillo bicolor usando una base de luz blanca/violeta.

# -----------------------------------------------------
# Optimizado por NVL
# -----------------------------------------------------

general {
    border_size = 2
    # El borde sigue siendo bicolor (Cian y Magenta)
    col.active_border = rgba(00fff7ff) rgba(1a0026ff) rgba(ff00ffff) 45deg
    col.inactive_border = rgba(0f0f2655)
}

decoration {
    shadow {
        enabled = true
        range = 20              # Aumentamos el rango para que el aura sea mayor
        render_power = 4        # Más potencia para que el brillo sea denso

        # --- EL TRUCO ---
        # Usamos un color "puente". Un blanco azulado muy transparente (44)
        # actúa como un foco detrás del borde. Al girar el cian y el rosa
        # sobre este blanco, parece que ambos emiten su propia luz.
        color = rgba(ffffff44)

        offset = 0 0
    }
}

animations {
    enabled = yes
    bezier = nv_neon_flow, 0.4, 0, 0.2, 1
    animation = borderangle, 1, 30, nv_neon_flow, loop
}
